"""Factories for the utilities app."""

__all__ = (
    "ImageFactory",
)

import random
import string

from factory.django import DjangoModelFactory
from factory.helpers import lazy_attribute

from utilities.models import Image

BLACK_PIXEL = (
    b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00'
    b'\x00\x01\x08\x00\x00\x00\x00:~\x9bU\x00\x00\x00\nIDATx\x9ccb'
    b'\x00\x00\x00\x06\x00\x0367|\xa8\x00\x00\x00\x00IEND\xaeB`\x82'
)


class ImageFactory(DjangoModelFactory):
    """
    Factory for the Image model.

    All the images that are generated by this factory will be
    PNGs with a single black pixel.
    """

    class Meta:
        model = Image

    mime = "PNG"
    data = BLACK_PIXEL

    @lazy_attribute
    def path(self):
        chars = string.ascii_lowercase + string.ascii_uppercase
        count = range(0, random.randrange(0, 255))

        return "".join(random.choice(chars) for _ in count) + ".png"
