# Generated by Django 2.2.5 on 2019-09-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('until', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete='sessions', to='companies.Company')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.QuestionSet')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.QuestionTheme')),
            ],
            options={
                'unique_together': {('company', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='questionset',
            name='theme',
            field=models.ManyToManyField(related_name='sets', to='activities.QuestionTheme'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.Answers')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.QuestionSet')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('deleted', models.DateTimeField(null=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='activities.Answers')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('answers', 'label'), ('answers', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='activities.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='activities.Session')),
            ],
            options={
                'unique_together': {('answerer', 'question', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to='activities.Answer')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='activities.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='activities.Session')),
            ],
            options={
                'unique_together': {('answerer', 'question', 'session')},
                'order_with_respect_to': 'question',
            },
        ),
    ]
