# Generated by Django 2.2.5 on 2019-10-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0002_auto_20190923_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answered',
            name='answerer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answered',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to='activities.Question'),
        ),
        migrations.AlterField(
            model_name='answered',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='activities.Session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answered',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='answers',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='activities.QuestionStyle'),
        ),
        migrations.CreateModel(
            name='AnsweredPlain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Session')),
            ],
            options={
                'unique_together': {('answerer', 'question', 'session')},
                'order_with_respect_to': 'question',
            },
        ),
    ]
