# Generated by Django 2.2.5 on 2019-10-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20191014_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionStyle',
            new_name='AnswerStyle',
        ),
    ]
