# Generated by Django 2.2.5 on 2019-10-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20191014_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
