# Generated by Django 2.2.5 on 2019-10-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_auto_20191014_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MetaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usermeta', to='analytics.MetaData')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='analytics.MetaLink')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='meta_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analytics.MetaType'),
        ),
    ]
