# Generated by Django 2.2.5 on 2019-10-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191014_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.Company'),
        ),
    ]
