# Generated by Django 2.2.5 on 2019-10-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20191015_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourtheme',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='companies.Company'),
        ),
    ]
